CREATE DATABASE IF NOT EXISTS cpe_control CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE cpe_control;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('USER','TI','ADMIN') NOT NULL DEFAULT 'USER',
  sector VARCHAR(120) NULL,
  unit VARCHAR(120) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Exemplo: docs (para futuro)
CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content LONGTEXT NULL,
  visibility ENUM('INTERNAL','SECTOR','PRIVATE','TI','RESTRICTED') NOT NULL DEFAULT 'INTERNAL',
  sector VARCHAR(120) NULL,
  owner_user_id BIGINT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_docs_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
);
